name: 'Weather Bot'
on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 2 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'GET Weather'
        run: |
          node ./weather.js
          cat ./result.html
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d $T')" >> $GITHUB_ENV
      - name: 'Send mail '
        uses: dawidd6/action-send-mail@master
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: CLZ
          to: 1926389897@qq.com
          from: CLZ
          html_body: file://result.html